spring:
  cloud:
    alicloud:  #阿里云oss配置
      access-key: LTAI4Fykx4yKZr1LHf15eJX5139
      secret-key: zhOs919PewfJGaXkU9vaqewvWzDoHO6611
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-ywst
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000



